twig:
    form_theme: ['bootstrap_4_layout.html.twig']
    exception_controller: null
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        mercure_publish_url: '%env(MERCURE_PUBLISH_URL)%'
        token_generator: '@App\Mercure\CookieGenerator'

        #app_path_articles_images: '%env(string:UPLOAD_PATH_ARTICLES)%'
        app_path_users_images: '%env(string:UPLOAD_PATH_USERS)%'
        app_path_default_images: '%env(string:UPLOAD_PATH_DEFAULT)%'

        site_name: 'Nomdesite'
        site_mail: 'Nomdesite@domain.fr'
        site_name_pretty: 'Nom de site'
