parameters:
    app.path.users_images: /uploads/images/users/

vich_uploader:
    db_driver: orm
    mappings:

        users_images:
            uri_prefix:         '%app.path.users_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/images/users'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        article_images:
            #uri_prefix:         '%app.path.article_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/images/articles/'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true


