easy_admin_bundle:
    #resource: 'App\Controller\AdminController.php'
    #Tres important de remplacer le controller pour ajouter les fonctionnalité de l'extension pack d'easy admin
    #resource: '@EasyAdminExtensionBundle/Controller/EasyAdminController.php'
    resource: 'App\Controller\AdminController'
    prefix: /admin
    type: annotation
