easy_admin:
  user:
    # this method/property must return the string representation of the user
    # (Symfony will look for getusername(), isusername(), ..., and 'username' property)
    name_property_path: 'username'
    display_avatar: false
  design:
    form_theme: # Both themes are for ckeditor integration
      - "@EasyAdmin/form/bootstrap_4.html.twig"
      - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
    menu:
      - label: 'Contenu'
        icon: 'newspaper-o'
        children:
          - {entity: 'Post', icon: 'scroll', label: 'Post', type_options: { entity: Post }}
          - {entity: 'PostToValidate', icon: 'scroll', label: 'Post à validé', type_options: { entity: PostToValidate }}
          - {entity: 'Comment', icon: 'comment', label: 'Commentaires', type_options: { entity: Comment }}
          - {entity: 'CommentToValidate', icon: 'comment', label: 'Commentaires à validé', type_options: { entity: CommentToValidate }}

      - label: 'Gestion'
        icon: 'cog'
        children:
          - {entity: 'User',  icon: 'user', label: 'Utilisateurs'}
          - {entity: 'MaillingList',  icon: 'envelope', label: 'Mails'}
#easy_admin_extension:
#  minimum_role: ROLE_ADMIN
