easy_admin:
  entities:
    Comment:
      class: App\Entity\Comment
      show:
        fields:
          - {property: 'approved' }
          - {property: 'textComment' }
          - {property: 'username' }
          - {property: 'user' }
          - {property: 'email' }
          - {property: 'createdAt' }
          - {property: 'post' }
          - {property: 'reports' }
      list:
        batch_actions: ['delete']
        dql_filter: 'entity.approved = 1 '
        actions: ['-new']
        fields:
          - 'approved'
          - 'created_at'
          - 'textComment'
          - 'user'
          - 'post'
          - 'reports'
          - 'likes'
      form:
        fields:
          - {property: 'approved' }
          - {property: 'textComment' }
          - {property: 'user' }
          - {property: post, label: 'Post' }


        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}

