easy_admin:
  entities:
    Post:
      class: App\Entity\Post
      show:
        fields:
          - {property: 'user' }
          - {property: 'text' }
          - {property: 'published' }
          - {property: 'createdAt' }
          - { property: comments, label: 'Commentaire', type: embedded_list,type_options: { entity: Comment } }

      list:
        batch_actions: ['delete']

        fields:
          - 'published'
          - 'user'
          - 'text'
          - 'createdAt'
          - 'reports'
          - 'comments'
          - 'likes'
      form:
        fields:
          - {property: 'user' }
          - {property: 'text' }
          - {property: 'published' }
          - {property: 'createdAt' }
          - { property: comments, label: 'Commentaire', type: embedded_list, type_options: { entity: Comment } }
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
          - {name: 'voir', icon: 'eye', label: false, css_class: 'btn btn-success' ,}
