easy_admin:
  entities:
    User:
      class: App\Entity\User
      show:
        fields:
          - {property: 'email' }
          - {property: 'username' }
          - {property: 'email' }
          - {property: 'roles' }
          - { property: posts, label: 'Posts', type: embedded_list }
          - { property: comments, label: 'Commentaires', type: embedded_list }

      list:
        batch_actions: ['delete']

        actions: ['-new']
        fields:
          - 'username'
          - 'email'
          - 'roles'
      password_encoding: { algorithm: 'bcrypt', cost: 12 }
      form:
        fields:
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN', 'ROLE_WRITER': 'ROLE_WRITER' } } }
          - { property: comments, label: 'Commentaires', type: embedded_list }
          - { property: posts, label: 'Posts', type: embedded_list }
